# public/admin/config.yml

# backend:
# name: git-gateway
# repo: karlthomaas/rental-decap-cms
# branch: main

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded med

# Here we define content structure
collections:
  - label: "Home page"
    name: "homepage"
    files:
      - label: "Hero"
        name: "hero"
        file: "src/content/homepage/hero.md" # Path to the markdown file
        create: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
              required: false,
            }
          - { label: "Button Text", name: "buttonText", widget: "string" }
