# public/admin/config.yml

local_backend: true

backend:
  name: git-gateway
  repo: tfmukles/parkquality
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images" # Location where files will be stored in the repo
public_folder: "public/images" # The src attribute for uploaded med

# Here we define content structure
collections:
  - label: "Home page"
    name: "homepage"
    files:
      - label: "Hero"
        name: "hero"
        file: "src/content/homepage/hero.md"
        create: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
              required: false,
            }
          - { label: "Button Text", name: "buttonText", widget: "string" }
